



spring:
  application:
    name: hello-spring-cloud-eureka
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zllshuaige/nz1905Serverconfig.git
          search-paths: respo

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/